### ISSUE TITLE
如何获得radarTrack.npy

### ISSUE THREAD

**Issue by Robyve** [RadarCameraFusionTeam-BUPT/FusionCalib#1]
您好：
感谢您杰出的论文和代码，我想请教一下：
1. 作为原始输入的radar轨迹追踪数据`radarTrack.npy`是如何获得的？是直接由radar硬件输出？还是经过软件处理后得到？
2. 如果我手中只有radar的点云数据，我该如何获得`radarTrack.npy`呢？

感激不尽！

**Comment by JiayinDeng** [comment]
感谢您的认可：

1、这一篇工作使用的硬件设备是Oculii的4D毫米波雷达，该雷达可以直接输出目标轨迹数据。

2、如果手中只有radar的点云，我建议使用一些传统的多扩展目标跟踪（MEOT）算法获取目标轨迹。比如：
TPMB-BP：https://github.com/yuhsuansia/Trajectory-PMB-EOT-BP
SPA：https://github.com/meyer-ucsd/EOT-TSP-21
TPMB-CA：https://github.com/yuhsuansia/Extended-target-PMBM-tracker
在车流量较小情况下，该算法可以获取准确的目标轨迹位置和速度。

BTW：我最近正在研究关于真实路侧下的多扩展目标跟踪算法，目前已经完成2所述所有算法在真实场景下的迁移，但由于我下一篇论文尚未发表，所以暂时不计划开源上述算法的实现，请谅解。

**Comment by Robyve** [comment]
> 感谢您的认可：
> 
> 1、这一篇工作使用的硬件设备是Oculii的4D毫米波雷达，该雷达可以直接输出目标轨迹数据。
> 
> 2、如果手中只有radar的点云，我建议使用一些传统的多扩展目标跟踪（MEOT）算法获取目标轨迹。比如： TPMB-BP：https://github.com/yuhsuansia/Trajectory-PMB-EOT-BP SPA：https://github.com/meyer-ucsd/EOT-TSP-21 TPMB-CA：https://github.com/yuhsuansia/Extended-target-PMBM-tracker 在车流量较小情况下，该算法可以获取准确的目标轨迹位置和速度。
> 
> BTW：我最近正在研究关于真实路侧下的多扩展目标跟踪算法，目前已经完成2所述所有算法在真实场景下的迁移，但由于我下一篇论文尚未发表，所以暂时不计划开源上述算法的实现，请谅解。

非常感谢！

**Comment by Guoc0529** [comment]
您好，我手上也有一款oculii的雷达，但是他不能输出增强点云，您能指导一下吗

**Comment by Robyve** [comment]
您好，我是该issue的提问者，对这方面了解比较少，建议您咨询原作者，谢谢！



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年04月11日 12:35 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>、State ***@***.***> |
| 主题 | Re: [RadarCameraFusionTeam-BUPT/FusionCalib] 如何获得radarTrack.npy (Issue #1) |

您好，我手上也有一款oculii的雷达，但是他不能输出增强点云，您能指导一下吗

**Comment by JiayinDeng** [comment]
> 您好，我手上也有一款oculii的雷达，但是他不能输出增强点云，您能指导一下吗

鉴于不同雷达的固件版本可能不同，我们建议您直接联系雷达代理商，获取SDK开发套件，从而输出增强的点云。

**Comment by Guoc0529** [comment]
代理不太懂，您可以把驱动发我一份吗 814243884@qq.com  万分感谢
